/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutPapierkorbRouteImport } from './routes/_layout/papierkorb'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAufgabenRouteImport } from './routes/_layout/aufgaben'
import { Route as LayoutAufgabenNeuRouteImport } from './routes/_layout/aufgaben/neu'
import { Route as LayoutAdminProjektRouteImport } from './routes/_layout/admin/projekt'
import { Route as LayoutAdminNutzerRouteImport } from './routes/_layout/admin/nutzer'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPapierkorbRoute = LayoutPapierkorbRouteImport.update({
  id: '/papierkorb',
  path: '/papierkorb',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAufgabenRoute = LayoutAufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAufgabenNeuRoute = LayoutAufgabenNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => LayoutAufgabenRoute,
} as any)
const LayoutAdminProjektRoute = LayoutAdminProjektRouteImport.update({
  id: '/admin/projekt',
  path: '/admin/projekt',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminNutzerRoute = LayoutAdminNutzerRouteImport.update({
  id: '/admin/nutzer',
  path: '/admin/nutzer',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aufgaben': typeof LayoutAufgabenRouteWithChildren
  '/dashboard': typeof LayoutDashboardRoute
  '/papierkorb': typeof LayoutPapierkorbRoute
  '/admin/nutzer': typeof LayoutAdminNutzerRoute
  '/admin/projekt': typeof LayoutAdminProjektRoute
  '/aufgaben/neu': typeof LayoutAufgabenNeuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/aufgaben': typeof LayoutAufgabenRouteWithChildren
  '/dashboard': typeof LayoutDashboardRoute
  '/papierkorb': typeof LayoutPapierkorbRoute
  '/admin/nutzer': typeof LayoutAdminNutzerRoute
  '/admin/projekt': typeof LayoutAdminProjektRoute
  '/aufgaben/neu': typeof LayoutAufgabenNeuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/aufgaben': typeof LayoutAufgabenRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/papierkorb': typeof LayoutPapierkorbRoute
  '/_layout/admin/nutzer': typeof LayoutAdminNutzerRoute
  '/_layout/admin/projekt': typeof LayoutAdminProjektRoute
  '/_layout/aufgaben/neu': typeof LayoutAufgabenNeuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/aufgaben'
    | '/dashboard'
    | '/papierkorb'
    | '/admin/nutzer'
    | '/admin/projekt'
    | '/aufgaben/neu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/aufgaben'
    | '/dashboard'
    | '/papierkorb'
    | '/admin/nutzer'
    | '/admin/projekt'
    | '/aufgaben/neu'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/aufgaben'
    | '/_layout/dashboard'
    | '/_layout/papierkorb'
    | '/_layout/admin/nutzer'
    | '/_layout/admin/projekt'
    | '/_layout/aufgaben/neu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/papierkorb': {
      id: '/_layout/papierkorb'
      path: '/papierkorb'
      fullPath: '/papierkorb'
      preLoaderRoute: typeof LayoutPapierkorbRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/aufgaben': {
      id: '/_layout/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof LayoutAufgabenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/aufgaben/neu': {
      id: '/_layout/aufgaben/neu'
      path: '/neu'
      fullPath: '/aufgaben/neu'
      preLoaderRoute: typeof LayoutAufgabenNeuRouteImport
      parentRoute: typeof LayoutAufgabenRoute
    }
    '/_layout/admin/projekt': {
      id: '/_layout/admin/projekt'
      path: '/admin/projekt'
      fullPath: '/admin/projekt'
      preLoaderRoute: typeof LayoutAdminProjektRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/nutzer': {
      id: '/_layout/admin/nutzer'
      path: '/admin/nutzer'
      fullPath: '/admin/nutzer'
      preLoaderRoute: typeof LayoutAdminNutzerRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutAufgabenRouteChildren {
  LayoutAufgabenNeuRoute: typeof LayoutAufgabenNeuRoute
}

const LayoutAufgabenRouteChildren: LayoutAufgabenRouteChildren = {
  LayoutAufgabenNeuRoute: LayoutAufgabenNeuRoute,
}

const LayoutAufgabenRouteWithChildren = LayoutAufgabenRoute._addFileChildren(
  LayoutAufgabenRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAufgabenRoute: typeof LayoutAufgabenRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutPapierkorbRoute: typeof LayoutPapierkorbRoute
  LayoutAdminNutzerRoute: typeof LayoutAdminNutzerRoute
  LayoutAdminProjektRoute: typeof LayoutAdminProjektRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAufgabenRoute: LayoutAufgabenRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutPapierkorbRoute: LayoutPapierkorbRoute,
  LayoutAdminNutzerRoute: LayoutAdminNutzerRoute,
  LayoutAdminProjektRoute: LayoutAdminProjektRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
